version: "3.2"

services:
    web:
        image: node:8.9-alpine
        environment:
            NODE_ENV: development
        volumes:
            - .:/usr/src/app
        command: npm start
        working_dir: /usr/src/app
        ports:
            - 3000:3000
